export type Affiliation = {
  image: string;
  name: string;
  type: "laboratory" | "university" | "company" | "funding";
  url: string;
};

export type Job = {
  applicationLink: string;
  detailLink?: string;
  detailText?: string;
  location?: string;
  postedAt?: string;
  shortDescription: string;
  status: "open" | "closed";
  title: string;
  // type: "full-time" | "part-time" | "internship";
};

export type MemberLinkType =
  | "website"
  | "email"
  | "github"
  | "linkedin"
  | "orcid"
  | "twitter"
  | "scholar";

export type Member = {
  affiliation?: string;
  advisor?: string;
  bio?: string;
  image: string;
  links?: Record<MemberLinkType, string>;
  name: string;
  researchInterests?: string[];
  title: string;
  type: "researcher" | "engineer" | "visiting" | "external";
};

export type ProjectId =
  | "pdc"
  | "aidrin"
  | "h5bench"
  | "drishti"
  | "s2d2"
  | "fadas"
  | "storehub"
  | "fastensor"

export type Project = {
  id: ProjectId;
  name: string;
  title: string;
  shortDescription: string;
  link: string;
  isCollaborative?: boolean;
  isFeatured?: boolean;
  isOurs?: boolean;
  researchStatus: "ready" | "testing" | "r&d";
  sourceLink?: string;
  status: "active" | "archived";
  tutorialLink?: string;
  type: "funded" | "student";
};

export type PublicationAuthor =
  |"S. Byna"
  |"A. Salimiparsa"
  |"A. Talukdar"
  |"H. Oh"
  |"K. Hiniduma"
  |"N. Lewis"
  |"R. Madduri"
  |"S. R. Sukumar"
  |"S. K. Saha"
  |"W. Zhang"
  |"C. D. Rickett"
  |"J. L. Bez" 
  |"D. Ryan"
  |"B. Dong"
  |"C. Egersdoerfer"
  |"A. Sareen"
  |"D. Xu"
  |"D. Dai"
  |"S. Breitenfeld"
  |"H. Tang"
  |"H. Zheng"
  |"J. Henderson"
  |"A. Nayak"
  |"V. R. Tribaldos"
  |"K. Wu"
  |"J. Ajo-Franklin"
  |"Q. Zhang"
  |"F. Guo"
  |"P. Dobson"
  |"A. Sim"
  |"R. Jain"
  |"A. Dhruv"
  |"C. Wang"
  |"K. Sanchez"
  |"A. Gavin"
  |"X. Zhang"
  |"R. Han"
  |"M. Zheng"
  |"Y. Chen"
  |"D. Kim"
  |"J. Hassoun"
  |"D.Thorsley"
  |"M. Wolf"
  |"W. Liao"
  |"K. Hou"
  |"Z. Huang"
  |"H. Ather"
  |"Y. Xia"
  |"N. Rajesh"
  |"K. Bateman"
  |"A. Kougkas"
  |"X. Sun"
  |"D. K. Sung"
  |"Y. Son"
  |"J. Wu"
  |"H. Eom"
  |"S. Kim"
  ;

export type PublicationTag =
  | "Accelerator"
  | "Access Pattern"
  | "Active Storage"
  | "Adaptive AI Model Checkpointing"
  | "AIDRIN"
  | "AI for I/O"
  | "AI Workflows"
  | "Apache Arrow"
  | "Bandwidth"
  | "Benchmark"
  | "Benchmarking"
  | "Best Paper Award"
  | "Big Data"
  | "Bipartite Graph"
  | "Burst Buffers"
  | "C-AMAT"
  | "Cache Management"
  | "Cache System"
  | "Characterization"
  | "ChronoLog"
  | "Cloud Application"
  | "Clouds and Distributed Computing"
  | "Coeus"
  | "Column store"
  | "Compression"
  | "Computer Architecture"
  | "Computing Education"
  | "Concurrency"
  | "Concurrent Average Memory Access Time"
  | "Concurrent Memory Access"
  | "Containers"
  | "Context Awareness"
  | "Coupled Training and Inferences"
  | "DNN"
  | "DNN Model Transferring"
  | "DRAM"
  | "Darshan"
  | "Data Access Pattern"
  | "Data Aggregation"
  | "Data Analytics"
  | "Data Centers"
  | "Data Compression"
  | "Data Drilling"
  | "Data Integration"
  | "Data Layout"
  | "Data Operator"
  | "Data Pipeline"
  | "Data Placement"
  | "Data Prefetching"
  | "Data Reorganization"
  | "Data Replication"
  | "Data Scoring"
  | "Data Streaming"
  | "Data-Aware"
  | "Data-Centric"
  | "Data-Centric Architecture"
  | "Data-Centric Design"
  | "Data-Fetching"
  | "Data-Intensive"
  | "Data-Reduction"
  | "Datalabels"
  | "Decoupled I/O"
  | "Deep Learning"
  | "Deep Memory Hierarchy"
  | "Deployment"
  | "Derived Variables"
  | "Disaggregated Memory"
  | "Distributed Data Structure"
  | "Distributed Log"
  | "Distributed Computing"
  | "Distributed Storage"
  | "DRAI"
  | "Dynamic"
  | "Dynamic Choice"
  | "Dynamic Programming"
  | "Efficiency"
  | "Elastic Storage"
  | "Elastic System"
  | "Emerging Architectures"
  | "Emerging Technologies"
  | "Energy-Aware I/O"
  | "Engine"
  | "Evolutionary Algorithms"
  | "Exascale I/O"
  | "Feature Reduction"
  | "File Scoring"
  | "Filesystems"
  | "Flash Memory"
  | "GPU"
  | "Graph Applications"
  | "Graph Computing"
  | "Graph Mining"
  | "Graph Pattern Matching"
  | "HDF5"
  | "HPC"
  | "HPC Analysis"
  | "HPC Data Containers"
  | "Hardware"
  | "Hardware Abstraction"
  | "Hardware Acceleration"
  | "Hermes"
  | "Heterogeneous Buffering"
  | "Heterogeneous I/O"
  | "Heterogeneous Systems"
  | "Hierarchical"
  | "Hierarchical Data Prefetching"
  | "Hierarchical Memory System"
  | "Hierarchical Storage"
  | "History of Computing"
  | "Hybrid Data Access Model"
  | "Hybrid Parallel File System"
  | "I/O"
  | "I/O Acceleration"
  | "I/O Analysis"
  | "I/O Behavior"
  | "I/O Bottleneck"
  | "I/O Bottleneck Detection"
  | "I/O Buffering"
  | "I/O Characterization"
  | "I/O Metrics"
  | "I/O Optimization"
  | "I/O Stack Tuning"
  | "I/O Tracing"
  | "In-Transit Computing"
  | "Inference Serving"
  | "Inferences During Partial Training"
  | "Integrated Workflow"
  | "Intelligent Selection"
  | "KV Cache"
  | "KVS"
  | "Label-Based I/O"
  | "Large-Scale I/O"
  | "Layered Buffering"
  | "Layered Performance Matching (LPM)"
  | "Libraries"
  | "Library"
  | "Lightweight"
  | "Linux"
  | "LLM Inference"
  | "Locality"
  | "MLP"
  | "Machine Learning"
  | "Matrix Multiplication"
  | "Maximal Biclique Enumeration"
  | "Metadata Management"
  | "Memory"
  | "Memory Architecture"
  | "Memory Concurrency"
  | "Memory Hierarchy"
  | "Memory Management"
  | "Memory Mapped I/O"
  | "Memory Performance Model"
  | "Memory System Optimization"
  | "Memory Stall Time"
  | "Memory-Bounded Speedup"
  | "Memory-Wall"
  | "Middleware"
  | "Modeling"
  | "Multi-Tiered"
  | "Novel Data Systems"
  | "Out-of-Core Analysis"
  | "Operating Systems"
  | "Optimization of Memory Architectures"
  | "Parallel File System (PFS)"
  | "Parallel I/O"
  | "Parallel Computing"
  | "Parallelism"
  | "Performance Evaluation"
  | "Performance Measurement"
  | "Performance Modeling"
  | "Performance Optimization"
  | "Persistent Memory"
  | "Phase Change Memory"
  | "Prefetch"
  | "Processing-in-Memory"
  | "Programming Frameworks"
  | "Pruning"
  | "Python"
  | "Quality of Service"
  | "Quantities of Interest"
  | "RAN"
  | "RPC over RDMA"
  | "ReRAM-based Accelerator"
  | "Reinforcement Learning"
  | "Representative"
  | "Resource Management"
  | "Resource Monitoring"
  | "Resource Provisioning"
  | "Scalability"
  | "Scalable Computing"
  | "Scientific Applications"
  | "Selection Algorithm"
  | "Server-Centric"
  | "Server-Push"
  | "Server-Side"
  | "Servers"
  | "Shared Log"
  | "Singularity"
  | "Solid State Drive"
  | "SpMM"
  | "Storage"
  | "Storage Auto-Tuning"
  | "Storage Bridging"
  | "Swapping"
  | "Synchronization"
  | "System Software"
  | "Task-Based I/O"
  | "Tensor"
  | "TensorFlow"
  | "Tiered Storage"
  | "Time Factors"
  | "Tools"
  | "UniMCC"
  | "Utilization"
  | "Virtualization"
  | "WisIO"
  | "Workflow Optimization"
  | "Workflow Priorities"
  | "Workflow-Aware"
  | "Workflows";

export type PublicationType =
  | "Conference"
  | "Journal"
  | "Book"
  | "Book Chapter"
  | "Poster"
  | "Technical Report"
  | "Thesis"
  | "WIP"
  | "Workshop";

export type Publication = {
  authors: PublicationAuthor[];
  title: string;
  venue: string;
  type: PublicationType;
  date: string;
  tags: PublicationTag[];
  links: Record<string, string>;
};
