export type Affiliation = {
  image: string;
  name: string;
  type: "laboratory" | "university" | "company" | "funding";
  url: string;
};

export type Job = {
  applicationLink: string;
  detailLink?: string;
  detailText?: string;
  location?: string;
  postedAt?: string;
  shortDescription: string;
  status: "open" | "closed";
  title: string;
  // type: "full-time" | "part-time" | "internship";
};

export type MemberLinkType =
  | "website"
  | "email"
  | "github"
  | "linkedin"
  | "orcid"
  | "twitter"
  | "scholar";

export type Member = {
  affiliation?: string;
  advisor?: string;
  bio?: string;
  image: string;
  links?: Record<MemberLinkType, string>;
  name: string;
  researchInterests?: string[];
  title: string;
  type: "researcher" | "engineer" | "visiting" | "external";
};

export type ProjectId =
  | "pdc"
  | "aidrin"
  | "h5bench"
  | "drishti"
  | "s2d2"
  | "fadas"
  | "storehub"
  | "fastensor"

export type Project = {
  id: ProjectId;
  name: string;
  title: string;
  shortDescription: string;
  link: string;
  isCollaborative?: boolean;
  isFeatured?: boolean;
  isOurs?: boolean;
  researchStatus: "ready" | "testing" | "r&d";
  sourceLink?: string;
  status: "active" | "archived";
  tutorialLink?: string;
  type: "funded" | "student";
};

export type PublicationAuthor =
  |"S. Byna"
  |"A. Salimiparsa"
  |"A. Talukdar"
  |"H. Oh"
  |"K. Hiniduma"
  |"N. Lewis"
  |"R. Madduri"
  |"S. R. Sukumar"
  |"S. K. Saha"
  |"W. Zhang"
  |"C. D. Rickett"
  |"J. L. Bez" 
  |"D. Ryan"
  |"B. Dong"
  |"C. Egersdoerfer"
  |"A. Sareen"
  |"D. Xu"
  |"D. Dai"
  |"S. Breitenfeld"
  |"H. Tang"
  |"H. Zheng"
  |"J. Henderson"
  |"A. Nayak"
  |"V. R. Tribaldos"
  |"K. Wu"
  |"J. Ajo-Franklin"
  |"Q. Zhang"
  |"F. Guo"
  |"P. Dobson"
  |"A. Sim"
  |"R. Jain"
  |"A. Dhruv"
  |"C. Wang"
  |"K. Sanchez"
  |"A. Gavin"
  |"X. Zhang"
  |"R. Han"
  |"M. Zheng"
  |"Y. Chen"
  |"D. Kim"
  |"J. Hassoun"
  |"D.Thorsley"
  |"M. Wolf"
  |"W. Liao"
  |"K. Hou"
  |"Z. Huang"
  |"H. Ather"
  |"Y. Xia"
  |"N. Rajesh"
  |"K. Bateman"
  |"A. Kougkas"
  |"X. Sun"
  |"D. K. Sung"
  |"Y. Son"
  |"J. Wu"
  |"H. Eom"
  |"S. Kim"
  |"Z. Li"
  |"A. Sinha"
  |"B. Swaminathan"
  |"J. Kang"
  |"K. Vaidya"
  |"A. Srinivasan"
  |"P. Kumar"
  |"D. Barbarash"
  |"C. Niu"
  |"S. Ibrahim"
  |"S. Idreos"
  |"T. Jones"
  |"K. Mohror"
  |"R. Ross"
  |"F. Rusu"
  |"J. Ravi" 
  |"Q. Koziol" 
  |"M. Becchi"
  |"B. Norris"
  |"M. K. H. Chowdhury"
  |"P. Bangalore"
  |"J. A. Harris"
  |"S. Jin"
  |"D. Tao"
  |"S. Di"
  |"Z. Lukic"
  |"F. Cappello"
  |"A. M. Karimi"
  |"A. K. Paul"
  |"B. Xie"
  |"P. Carns"
  |"S. Oral"
  |"F. Wang"
  |"J. Hanley"
  |"A. Popescu"
  |"Imperial Valley Dark Fiber Team"
  |"V. Vishwanath"
  |"J. Mainzer"
  |"A. Bashyal" 
  |"P. Van Gemmeren"
  |"S. Sehrish"
  |"K. Knoepfel"
  |"Q. Kang"
  |"J. Tian"
  |"T. Li"
  |"B. Fang"
  |"D. Wang"
  |"Z. Zhang"
  |"Q. Guan"
  |"S. Krishnamoorthy"
  |"S. Kannan"
  |"J. Lofstead"
  |"C. Xu"
  |"S. Bhattacharya"
  |"M. Foltin"
  |"P. Faraboschi"
  |"D. Williams-Young"
  |"R. Latham"
  |"H. Sim"
  |"S. Lee"
  |"S. Vazhkudai"
  |"J. Bang"
  |"C. Kim"
  |"H. Sung"
  |"B. Enders"
  |"D. Bard"
  |"C. Snavely"
  |"L. Gerhardt"
  |"J. Lee"
  |"B. Totzke"
  |"K. Antypas"
  |"R. Cheema"
  |"S. Cholia"
  |"M. Day"
  |"A. Gaur"
  |"A. Greiner"
  |"T. Groves"
  |"M. Kiran"
  |"K. Rowland"
  |"D. Skinner"
  |"R. Thomas"
  |"G. Torok"
  |"C. Samuel"
  |"A. Selvarajan"
  |"J. Mu"
  |"J. Soumagne"
  |"R. Warren"
  |"D. Kang"
  |"O. Rübel"
  |"S. Blanas"
  |"X. Xing"
  |"T. Patel"
  |"G. K. Lockwood"
  |"N. J. Wright"
  |"D. Tiwari"
  |"M. S. Breitenfeld"
  |"E. Pourmal"
  |"D. Robinson"
  |"S. Bailey"
  |"S. Snyder"
  |"M. Agarwal"
  |"D. Singhvi"
  |"P. Malakar"
  |"J. Liu"
  |"B. Williams"
  |"N. Fortner"
  |"G. Heber"
  |"M. Paterno"
  |"T. Wang"
  |"G. Lockwood"
  |"N. Wright"
  |"P. F. Heiner Kilian"
  |"X. Li"
  |"B. Behzad"
  |"Prabhat"
  |"M. Snir"
  |"B. Yildiz"
  |"A. Shoshani"
  |"H. Xing"
  |"S. Floratos"
  |"P. Brown"
  |"J. S. Vetter"
  |"R. Brightwell"
  |"M. Gokhale"
  |"P. McCormick"
  |"J. Shalf"
  |"K. Mu"
  |"F. Tessier"
  |"Y. Cheng"
  |"G. Butler"
  |"M. Chaarawi"
  |"K. Kallback-Rose"
  |"D. Hazen"
  |"F. Chowdhury"
  |"T. Kurth"
  |"S. Farrell"
  |"W. Yu"
  |"D. Donofrio"
  |"A. Dubey"
  |"T. Humble"
  |"C. Schuman"
  |"B. Van Essen"
  |"S. Yoo"
  |"A. Aiken"
  |"D. Bernholdt"
  |"K. Cameron"
  |"F. Cappello"
  |"B. Chapman"
  |"A. Chien"
  |"M. Hall"
  |"R. Hartman-Baker"
  |"Z. Lan"
  |"M. Lang"
  |"J. Leidel"
  |"S. Li"
  |"R. Lucas"
  |"J. Mellor-Crummey"
  |"P. Peltz Jr."
  |"T. Peterka"
  |"M. Strout"
  |"J. Wilke"
  |"B. Wadhwa"
  |"A. R. Butt"
  |"W. Yoo"
  |"K. Harms"
  |"Z. Nault"
  |"W. Zhao"
  |"F. Willmore"
  |"W. Bhimji"
  |"B. Cook"
  |"B. Austin"
  |"B. Thakur"
  |"J. Deslippe"
  |"O. Kulkarni"
  |"V. Venkatesan"
  |"R. Sisneros"
  |"K. Chadalavada"
  |"H. Johansen"
  |"J.N. Johnson"
  |"N. Keen"
  |"S. Ranshous"
  |"D.F. Martin"
  |"S. Klasky"
  |"N.F. Samatova"
  |"S. Harenberg"
  |"X. Zou"
  |"D. Devendran"
  |"D. Trebotich"
  |"N. Samatova"
  |"M.M.A. Patwary"
  |"N.R. Satish"
  |"N. Sundaram"
  |"P. Sadowski"
  |"E. Racah"
  |"C. Tull"
  |"P. Dubey"
  |"O. Rubel"
  |"K. Bouchard"
  |"D. Martin"
  |"B. van Straalen"
  |"M. Romanus"
  |"D. Paul"
  |"A. Ovsyannikov"
  |"B. Friesen"
  |"M. Bryson"
  |"J. Correa"
  |"G.K. Lockwood"
  |"V. Tsulaia"
  |"R.S. Canon"
  |"A. Gittens"
  |"M.F. Ringenburg"
  |"D. Boyuka"
  |"D. Desai"
  |"K. Bansal"
  |"D. Gursoy"
  |"C. Daley"
  |"V. Beckner"
  |"S. Jeon"
  |"J. Gu"
  |"W. Collins"
  |"M. Wehner"
  |"V. Roytershteyn"
  |"M.J. Anderson"
  |"Y. Yao"
  |"M. Mubarak"
  |"C. Carothers"
  |"H.V.T. Luu"
  |"H. Krishnan"
  |"T. O'Brien"
  |"B. Loring"
  |"D. Stone"
  |"Y. Liu"
  |"J. Johnson"
  |"C. Paciorek"
  |"J. Kim"
  |"S. Wild"
  |"H. Luu"
  |"M. Winslett"
  |"W. Gropp"
  |"E. Dart" 
  |"D. Boyuka II"
  |"T. Ligocki"
  |"M.S. Breitenfeld"
  |"H.T. Chiu"
  |"J. Chou"
  |"T. Habermann"
  |"A. Collette"
  |"S. Vincena"
  |"W. Benger"
  |"J.J. Billings"
  |"M. Gerring"
  |"K. Hinsen"
  |"P. de Buyl"
  |"M. Könnecke"
  |"F. Maia"
  |"W.D. Collins"
  |"M.F. Wehner"
  |"W. Bethel"
  |"J. Huchette"
  |"R. Aydt"
  |"J.L. Liu"
  |"K.W. Lin"
  |"A. Uselton"
  |"D. Knaak"
  |"Y. He"
  |"W. D. Collins"
  |"H. Karimabadi"
  |"W.S. Daughton"
  |"M. Howison"
  |"J. Hsu"
  |"K. Schuchardt"
  |"P. Bremer"
  |"F. Li"
  |"J. Patchett"
  |"H-W. Shen"
  |"D. Pugmire"
  |"D. Williams"
  |"J. Qiang"
  |"R. D. Ryne"
  |"C. G. R. Geddes"
  |"E. Cormier-Michel"
  |"T. Yopes"
  |"Y. Yin"
  |"H. Song"
  |"G. Weber"
  |"G. Ostrouchov"
  |"R. Strelitz"
  |"D. Rotem"
  |"M. Balman"
  |"D. Li"
  |"S. Chakradar"
  |"S. Cadambi"
  |"J. Meng"
  |"A. Raghunathan"
  |"Z. Fang"
  |"D. Holmgren"
  |"R. Nakhoul"
  |"K. Velusamy"
  ;

export type PublicationTag =
  | "Accelerator"
  | "Access Pattern"
  | "Active Storage"
  | "Adaptive AI Model Checkpointing"
  | "AIDRIN"
  | "AI for I/O"
  | "AI Workflows"
  | "Apache Arrow"
  | "Bandwidth"
  | "Benchmark"
  | "Benchmarking"
  | "Best Paper Award"
  | "Big Data"
  | "Bipartite Graph"
  | "Burst Buffers"
  | "C-AMAT"
  | "Cache Management"
  | "Cache System"
  | "Characterization"
  | "ChronoLog"
  | "Cloud Application"
  | "Clouds and Distributed Computing"
  | "Coeus"
  | "Column store"
  | "Compression"
  | "Computer Architecture"
  | "Computing Education"
  | "Concurrency"
  | "Concurrent Average Memory Access Time"
  | "Concurrent Memory Access"
  | "Containers"
  | "Context Awareness"
  | "Coupled Training and Inferences"
  | "DNN"
  | "DNN Model Transferring"
  | "DRAM"
  | "Darshan"
  | "Data Access Pattern"
  | "Data Aggregation"
  | "Data Analytics"
  | "Data Centers"
  | "Data Compression"
  | "Data Drilling"
  | "Data Integration"
  | "Data Layout"
  | "Data Operator"
  | "Data Pipeline"
  | "Data Placement"
  | "Data Prefetching"
  | "Data Reorganization"
  | "Data Replication"
  | "Data Scoring"
  | "Data Streaming"
  | "Data-Aware"
  | "Data-Centric"
  | "Data-Centric Architecture"
  | "Data-Centric Design"
  | "Data-Fetching"
  | "Data-Intensive"
  | "Data-Reduction"
  | "Datalabels"
  | "Decoupled I/O"
  | "Deep Learning"
  | "Deep Memory Hierarchy"
  | "Deployment"
  | "Derived Variables"
  | "Disaggregated Memory"
  | "Distributed Data Structure"
  | "Distributed Log"
  | "Distributed Computing"
  | "Distributed Storage"
  | "DRAI"
  | "Dynamic"
  | "Dynamic Choice"
  | "Dynamic Programming"
  | "Efficiency"
  | "Elastic Storage"
  | "Elastic System"
  | "Emerging Architectures"
  | "Emerging Technologies"
  | "Energy-Aware I/O"
  | "Engine"
  | "Evolutionary Algorithms"
  | "Exascale I/O"
  | "Feature Reduction"
  | "Federated Learning"
  | "File Scoring"
  | "Filesystems"
  | "Flash Memory"
  | "GPU"
  | "Graph Applications"
  | "Graph Computing"
  | "Graph Mining"
  | "Graph Pattern Matching"
  | "HDF5"
  | "HPC"
  | "HPC Analysis"
  | "HPC Data Containers"
  | "Hardware"
  | "Hardware Abstraction"
  | "Hardware Acceleration"
  | "Hermes"
  | "Heterogeneous Buffering"
  | "Heterogeneous I/O"
  | "Heterogeneous Systems"
  | "Hierarchical"
  | "Hierarchical Data Prefetching"
  | "Hierarchical Memory System"
  | "Hierarchical Storage"
  | "History of Computing"
  | "Hybrid Data Access Model"
  | "Hybrid Parallel File System"
  | "I/O"
  | "I/O Acceleration"
  | "I/O Analysis"
  | "I/O Behavior"
  | "I/O Bottleneck"
  | "I/O Bottleneck Detection"
  | "I/O Buffering"
  | "I/O Characterization"
  | "I/O Metrics"
  | "I/O Optimization"
  | "I/O Stack Tuning"
  | "I/O Tracing"
  | "In-Transit Computing"
  | "Inference Serving"
  | "Inferences During Partial Training"
  | "Integrated Workflow"
  | "Intelligent Selection"
  | "KV Cache"
  | "KVS"
  | "Label-Based I/O"
  | "Large-Scale I/O"
  | "Layered Buffering"
  | "Layered Performance Matching (LPM)"
  | "Libraries"
  | "Library"
  | "Lightweight"
  | "Linux"
  | "LLM Inference"
  | "Locality"
  | "MLP"
  | "Machine Learning"
  | "Matrix Multiplication"
  | "Maximal Biclique Enumeration"
  | "Metadata Management"
  | "Memory"
  | "Memory Architecture"
  | "Memory Concurrency"
  | "Memory Hierarchy"
  | "Memory Management"
  | "Memory Mapped I/O"
  | "Memory Performance Model"
  | "Memory System Optimization"
  | "Memory Stall Time"
  | "Memory-Bounded Speedup"
  | "Memory-Wall"
  | "Middleware"
  | "Modeling"
  | "Multi-Tiered"
  | "Novel Data Systems"
  | "Out-of-Core Analysis"
  | "Operating Systems"
  | "Optimization of Memory Architectures"
  | "Parallel File System (PFS)"
  | "Parallel I/O"
  | "Parallel Computing"
  | "Parallelism"
  | "Performance Evaluation"
  | "Performance Measurement"
  | "Performance Modeling"
  | "Performance Optimization"
  | "Persistent Memory"
  | "Phase Change Memory"
  | "Prefetch"
  | "Processing-in-Memory"
  | "Programming Frameworks"
  | "Pruning"
  | "Python"
  | "Quality of Service"
  | "Quantities of Interest"
  | "RAN"
  | "RPC over RDMA"
  | "ReRAM-based Accelerator"
  | "Reinforcement Learning"
  | "Representative"
  | "Resource Management"
  | "Resource Monitoring"
  | "Resource Provisioning"
  | "Scalability"
  | "Scalable Computing"
  | "Scientific Applications"
  | "Selection Algorithm"
  | "Server-Centric"
  | "Server-Push"
  | "Server-Side"
  | "Servers"
  | "Shared Log"
  | "Singularity"
  | "Solid State Drive"
  | "SpMM"
  | "Storage"
  | "Storage Auto-Tuning"
  | "Storage Bridging"
  | "Swapping"
  | "Synchronization"
  | "System Software"
  | "Task-Based I/O"
  | "Tensor"
  | "TensorFlow"
  | "Tiered Storage"
  | "Time Factors"
  | "Tools"
  | "UniMCC"
  | "Utilization"
  | "Virtualization"
  | "WisIO"
  | "Workflow Optimization"
  | "Workflow Priorities"
  | "Workflow-Aware"
  | "Workflows";

export type PublicationType =
  | "Conference"
  | "Journal"
  | "Book"
  | "Book Chapter"
  | "Poster"
  | "Technical Report"
  | "Thesis"
  | "WIP"
  | "Workshop"
  | "Keynote"
  | "Position"
  | "Presentation"
  | "Invited";

export type Publication = {
  authors: PublicationAuthor[];
  title: string;
  venue: string;
  type: PublicationType;
  date: string;
  tags: PublicationTag[];
  links: Record<string, string>;
};
