name: Build Check for Docusaurus

on:
  pull_request:
    branches:
      - main

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Docusaurus build
        run: npm run build