name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      
      - name: Configure git remote with PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/idtlab/idtlab.github.io.git

      - name: Deploy with Docusaurus
        env:
          GIT_USER: idtlab
          DEPLOYMENT_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: npm run deploy
